### ISSUE TITLE
how to set 24 hour time format? Is this possible?

### ISSUE THREAD

**Issue by TarunDas284** [henninghall/react-native-date-picker#47] opened 2019-04-15 04:34 UTC

**Comment by henninghall** [comment] 2019-04-15 05:18
Duplicate of https://github.com/henninghall/react-native-date-picker/issues/41

**Closed by henninghall** 2019-04-15 05:18 UTC

**Comment by club9822** [comment] 2019-11-03 05:35
just do this in `con.henninghall.date_picker.wheels.Setting.java`

public class Settings {
    public static boolean usesAmPm (){
        return false;
        // return !DateFormat.is24HourFormat(DatePickerManager.context);
    }
}

**Comment by henninghall** [comment] 2019-11-03 09:17
@club9822 That would only work on Android though.
