### ISSUE TITLE
 Could not find com.github.henninghall:numberpickerview:v1.1.5.

### ISSUE THREAD

**Issue by DTeixeira2000** [henninghall/react-native-date-picker#749] opened 2024-01-03 23:01 UTC
Please help me with this when i try to sync in react native and android studio

 Could not find com.github.henninghall:numberpickerview:v1.1.5.
     Required by:
         project :react-native-date-picker

**Comment by henninghall** [comment] 2024-01-08 11:24
Duplicate of https://github.com/henninghall/react-native-date-picker/issues/396

**Closed by henninghall** 2024-01-08 11:24 UTC
