### ISSUE TITLE
Error while using in IOS 

### ISSUE THREAD

**Issue by stuart-ithands** [henninghall/react-native-date-picker#241] opened 2020-09-16 07:30 UTC
Property 'preferredDatePickerStyle' not found on object of type 'DatePicker 

Use of undeclared identifier 'UIDatePickerStyleWheels'

 if(@available(iOS 14, *)) {
            self.preferredDatePickerStyle = UIDatePickerStyleWheels;     // Error here
        }

**Comment by henninghall** [comment] 2020-09-16 16:58
Duplicate of https://github.com/henninghall/react-native-date-picker/issues/224

**Closed by henninghall** 2020-09-16 16:58 UTC
