### ISSUE TITLE
Locale does not work for Time Picker on iOS 16.5

### ISSUE THREAD

**Issue by wojciechkrol** [henninghall/react-native-date-picker#669] opened 2023-06-29 10:49 UTC
**Describe the bug**
I have an iPhone device with iOS 16.5 and Time Picker does not consider my locale prop. I don't know what iOS version broke this but my iOS 16.2 simulator displays the correct Time based on locale prop.

**Expected behavior**
I have set the device locale to USA (with AM/PM times) on both devices (iOS 16.5 and iOS 16.2). In the application, I defined:
```
mode="time"
is24hourSource="locale"
locale="pl"
```
On iOS 16.2 time picker displays the correct 24h format while iOS 16.5 displays device defined locale (with AM/PM)

**To Reproduce**
```javascript
export default class App extends Component {

  state = { date: new Date() }

  render = () =>
    <DatePicker
      date={this.state.date}
      onDateChange={date => this.setState({ date })}
      androidVariant="iosClone"
      textColor="#000"
      mode="time"
      is24hourSource="locale"
      locale="pl"
    />

}
```

**Smartphone (please complete the following information):**
 - OS: iOS 16.5.1
 - React Native version: 0.66.5
 - react-native-date-picker version: 4.2.13

**Comment by henninghall** [comment] 2023-06-29 13:18
Duplicate of https://github.com/henninghall/react-native-date-picker/issues/665

**Closed by henninghall** 2023-06-29 13:18 UTC
