### ISSUE TITLE
On button press, I receive the error: TypeError: null is not an object (evaluating '_reactNative.NativeModules.RNDatePicker.openPicker')

### ISSUE THREAD

**Issue by Tahmid11** [henninghall/react-native-date-picker#628] opened 2023-03-27 16:01 UTC
I am not using the expo go app but I am using it on it expo development builds (for example I run my application using :'npx expo start --dev-client'.

I have used the same code as the github documentation, and I still receive errors. 

Terminal Output:
<img width="436" alt="Screenshot 2023-03-27 at 17 06 24" src="https://user-images.githubusercontent.com/73365097/227998956-0697818c-6d76-49d7-9df3-f6673e33bdea.png">

The Operating System is Android (android emulator).
I am using Expo Development Servers.

Thanks.

**Comment by henninghall** [comment] 2023-04-01 08:28
Duplicate of https://github.com/henninghall/react-native-date-picker/issues/404

**Closed by henninghall** 2023-04-01 08:28 UTC
