### ISSUE TITLE
TypeError: Object(...) is not a function

### ISSUE THREAD

**Issue by glitchwizard** [henninghall/react-native-date-picker#230] opened 2020-08-19 00:27 UTC
**Describe the bug**
Using Expo and Typescript in my project, I followed the instructions on how to set it up in a simple component, and I'm getting the following error: 

![image](https://user-images.githubusercontent.com/40527412/90578230-a1322f80-e177-11ea-9261-e68589929a8d.png)

And when I use an android emulator, it looks like this

![image](https://user-images.githubusercontent.com/40527412/90578245-aee7b500-e177-11ea-8c16-13a0c0548cda.png)

**Expected behavior**
The expected behavior would be that the date picker component adds without issue, when following the installation instructions.

**To Reproduce**
Add example code that reproduces the behavior. 
```import React, { useState } from 'react';
import Background from './components/background';
import { StyleSheet, View, Text, StatusBar } from 'react-native';
import Icon from 'react-native-vector-icons/MaterialCommunityIcons';
import DatePicker from 'react-native-date-picker';
//@ts-ignore not sure how to fix this issue just yet
import WeekdayPicker from "./react-native-weekday-picker"; //forked from https://www.npmjs.com/package/react-native-weekday-picker


<link href="https://fonts.googleapis.com/css2?family=Lato:wght@300&display=swap" rel="stylesheet"></link>

export default function App() {
  
  let days = {
    0: 0,
    1: 0,
    2: 1,
    3: 0,
    4: 0,
    5: 0,
    6: 0
  };
  
  const handleChange = (days: {}) => { this.setState(days) };

  const [date, setDate] = useState(new Date());

  return (
    <View style={styles.container}>
      <View style={styles.calApptComponentContainer}>
        <View style={styles.calHeader}>
          <Text style={{ borderColor: "green", borderWidth: 1, flex: 1 }}>
            Tues, Jan 14
          </Text>
          <View
            style={{
              borderColor: "purple",
              borderWidth: 1,
              flex: 1,
              alignItems: "flex-end",
            }}
          >
            <Icon name="calendar-blank" size={30} color="#000" />
          </View>
        </View>
            <WeekdayPicker
              days={days}
              /*-- onChange={handleChange}  //can't figure out how to get this to work just yet --*/
              style={styles.picker}
              dayStyle={styles.day}
            />
        <View style={styles.calMeetingTimeSelectorContainer}>
          <Text>CalMeetingTimeSelector</Text>
            
        </View>
        <DatePicker
          date={date}
          onDateChange={setDate}
        />
        <View style={styles.calFooter}>
          <Text>CalFooter</Text>
        </View>
      </View>
      <Background />
      <StatusBar />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    fontFamily: 'Lato, sans-serif',
  },
  calApptComponentContainer: {
    borderWidth: 1,
    borderColor: "red",
    flex: 1,
    justifyContent: "center",
    alignItems: "stretch",
  },
  calHeader: {
    paddingTop: 50,
    flex: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: 'stretch',
  },
  calWeekdayItemText: {
    flex: 1,
    fontSize: 20,
    textAlign: "center"
  },
  calWeekdaySelector:{
    flex: 1,
    flexDirection: "row",
    borderColor: "yellowgreen",
    borderWidth: 1,
    justifyContent: "center",
    alignItems: "center",
    alignContent: 'center',
    paddingLeft: 20,
    paddingRight: 20,
  },
  calMeetingTimeSelectorContainer: {
    flex: 2,
    borderWidth: 1,
    borderColor: "orange",
  },
  calFooter: {
    flex: 1,
    borderWidth: 1,
    borderColor: "yellow",
  },
  picker: {
    padding: 30
  },
  day: {
    margin: 5
  }
});
```

**Smartphone (please complete the following information):**
 - OS: Android sdk_gphone_x86 , Virtual device from Android Studio. Pixel 2 API 30
![image](https://user-images.githubusercontent.com/40527412/90578405-19005a00-e178-11ea-955f-c03218faeb79.png)
 - React Native version: 0.62.2
 - react-native-date-picker version: 3.1.0

**Comment by glitchwizard** [comment] 2020-08-19 00:44
Just as a test, I went and created a brand new expo project using Expo Init, and still got the same error when the source code in "App.tsx" was just the following: 

```
import { StatusBar } from 'expo-status-bar';
import React, { useState } from 'react';
import { StyleSheet, View } from 'react-native';
import DatePicker from 'react-native-date-picker';

export default function App() {

  const [date, setDate] = useState(new Date())

  return (
    <View style={styles.container}>
      <DatePicker 
        date={date}
        onDateChange={setDate}
      />
      <StatusBar style="auto" />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
```

Wanted to make sure it wasn't something else in my app that might be conflicting, but it looks like this is an issue from the package and not my project. 

Here's a screenshot of the emulator: 
![image](https://user-images.githubusercontent.com/40527412/90579289-6d0c3e00-e17a-11ea-9e51-1059fad87ff9.png)

**Comment by henninghall** [comment] 2020-08-19 05:43
Duplicate of https://github.com/henninghall/react-native-date-picker/issues/11

**Closed by henninghall** 2020-08-19 05:43 UTC
