### ISSUE TITLE
Date picker is not showing correctly on iOS

### ISSUE THREAD

**Issue by LuisC360** [henninghall/react-native-date-picker#294] opened 2021-02-15 19:03 UTC
I have an issue regarding date-picker on iOS, the picker is not showing correctly on screen (see the attached picture), while on Android works perfectly fine. 

I'm using the example from the main page.

Currently I'm working with v2.7.8, alongside react-native v0.62.2 and React v16.11.0. iOS v14.4 and Android v10

![WhatsApp Image 2021-02-15 at 11 36 37 AM](https://user-images.githubusercontent.com/15643216/107984616-ea7c0400-6f8d-11eb-95f2-0e696a9b926e.jpeg)

**Comment by henninghall** [comment] 2021-02-15 19:10
Hi, try updating to latest version of this package, did it help?

**Comment by henninghall** [comment] 2021-02-15 19:26
Duplicate of https://github.com/henninghall/react-native-date-picker/issues/212 

Fixed in latest version

**Closed by henninghall** 2021-02-15 19:26 UTC
