### ISSUE TITLE
Select month and year only

### ISSUE THREAD

**Issue by lineuxyz** [henninghall/react-native-date-picker#321] opened 2021-05-04 22:02 UTC
## Feature request

Add the possibility to select only month and year, I use this lib in a project and I needed to replace it because it does not have this type of property, I needed to create a new one for my case, it would be interesting to add.

**Comment by henninghall** [comment] 2021-05-05 05:24
Duplicate of https://github.com/henninghall/react-native-date-picker/issues/17

**Closed by henninghall** 2021-05-05 05:24 UTC
