### ISSUE TITLE
"was not found in the UIManager."  For Android

### ISSUE THREAD

**Issue by XOneto9** [henninghall/react-native-date-picker#180] opened 2020-04-09 10:13 UTC
I have error 
"requireNativeComponent: "DatePickerManager" was not found in the UIManager."

on Android.

When I start iOS also get this error, But I inserted "pod `react-native-date-picker` on cocoapod file. So I solve the problem for ios.
but still, I have trouble for Android .

how should I solve it?

<img width="277" alt="스크린샷 2020-04-09 오후 7 07 53" src="https://user-images.githubusercontent.com/18350072/78884575-1be69200-7a96-11ea-9c7d-69a486526e2f.png">

```

**Smartphone (please complete the following information):**
 - OS: [Android]
 - React Native version: sdk-36.0.1
 - react-native-date-picker version : 2.7.9

**Comment by henninghall** [comment] 2020-04-10 08:14
Duplicate of https://github.com/henninghall/react-native-date-picker/issues/107

**Closed by henninghall** 2020-04-10 08:14 UTC
