### ISSUE TITLE
DatePicker

### ISSUE THREAD

**Issue by Hammad-012** [henninghall/react-native-date-picker#706] opened 2023-10-02 06:42 UTC
TypeError: NativePicker.openPicker is not a function (it is undefined)

**Comment by Hammad-012** [comment] 2023-10-02 06:43
<TouchableOpacity onPress={() => setOpen(true)}>
                    <Text style={{color:'#666', marginLeft:5,marginTop:5}}>Date of Birth</Text>
                    </TouchableOpacity>
                    </View>
                    <DatePicker
                      modal
                      mode="date"
                      open={open}
                      date={date}
                      onConfirm={(date) => {
                        setOpen(false);
                        setDate(date);
                      }}
                      onCancel={() => {
                        setOpen(false);
                      }}
                  />

**Comment by Hammad-012** [comment] 2023-10-02 06:47
<TouchableOpacity onPress={() => setOpen(true)}>
                    <Text style={{color:'#666', marginLeft:5,marginTop:5}}>Date of Birth</Text>
                    </TouchableOpacity>
                    </View>
                    <DatePicker
                      modal
                      mode="date"
                      open={open}
                      date={date}
                      onConfirm={(date) => {
                        setOpen(false);
                        setDate(date);
                      }}
                      onCancel={() => {
                        setOpen(false);
                      }}
                  />

**Comment by henninghall** [comment] 2023-10-02 07:11
Duplicate of https://github.com/henninghall/react-native-date-picker/issues/404

**Closed by henninghall** 2023-10-02 07:11 UTC

**Comment by Fashad-Ahmed** [comment] 2024-01-01 12:51
@Hammad-012  does it solves your issue. @henninghall I am facing the same issue and provided solution doesn't seemed to work for me.
