### ISSUE TITLE
Invariant violation: requireNativeComponent "DatePickerManager" was not found in the UIManager

### ISSUE THREAD

**Issue by charbelsako** [henninghall/react-native-date-picker#215] opened 2020-07-24 13:21 UTC
Why is this error occurring?
I can provide with more info.

**Comment by henninghall** [comment] 2020-07-26 17:26
Duplicate of https://github.com/henninghall/react-native-date-picker/issues/44

**Closed by henninghall** 2020-07-26 17:26 UTC

**Comment by charbelsako** [comment] 2020-07-27 11:36
do I have to run it from Xcode?

**Comment by henninghall** [comment] 2020-07-27 17:03
No that should not be necessary
