### ISSUE TITLE
Cannot change confirm and cancel button color

### ISSUE THREAD

**Issue by juliengbt** [henninghall/react-native-date-picker#654] opened 2023-05-05 11:25 UTC
**Describe the bug**
The colorAccent style is not applying on the button of the modal in Android

**Expected behavior**
The color should be applied to the button.
Also it would be better to change the button color from DatePickerTheme instead of the AppTheme. So the accentColor wouldn't apply on the whole app but just on the DatePicker component.

**To Reproduce**
File styles.xml
```xml
<resources xmlns:tools="http://schemas.android.com/tools">
  <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
    ...
    <item name="colorAccent">#00ff00</item>
  </style>
</resources>
```

**Smartphone (please complete the following information):**
 - OS: Android
 - React Native version 0.71.7
 - react-native-date-picker version 4.2.12

**Comment by henninghall** [comment] 2023-05-23 17:51
Duplicate of https://github.com/henninghall/react-native-date-picker/issues/583

**Closed by henninghall** 2023-05-23 17:51 UTC

**Comment by grandbudha** [comment] 2023-10-23 15:34
Hello, 
I was facing the same issue with version **4.3.3** and I tried everything, nothing worked for me.
Here what worked for me -
1. Go to _react-native-date-picker_ under _node_modules_ and inside java you will find the java file with name => **DatePickerModuleImpl.java.**

2. Look for public void **openPicker**(ReadableMap props){}
3. Inside the above method, you will find dialog.show(), add below lines (note, they are for both negative and positive buttons, i.e., Confirm and Cancel button) 
        **dialog.getButton(AlertDialog.BUTTON_POSITIVE).setTextColor(Color.rgb(194,73,100));
        dialog.getButton(AlertDialog.BUTTON_NEGATIVE).setTextColor(Color.rgb(194,73,100));**
4. Your color code will go inside Color.rgb, if you have Hex color, then you can convert it easily.
5. Add this import => **import android.graphics.Color;**

Thank you.
