### ISSUE TITLE
_reactNative.NativeModules.RNDatePicker.openPicker shows null is not an object 

### ISSUE THREAD

**Issue by romandev142** [henninghall/react-native-date-picker#702] opened 2023-09-18 05:55 UTC
**Describe the bug**
When try to run on IOS device/simulator getting an error like

**TypeError: null is not an object (evaluating '_reactNative.NativeModules.RNDatePicker.openPicker')**

This error is located at:
    in DatePickerIOS (at src/index.js:17)
    in DatePickerWrapper (at EditProfileScreen.js:366)
    in RCTView (at View.js:32)
    in View (at EditProfileScreen.js:353)
    in RCTView (at View.js:32)
    in View (at EditProfileScreen.js:201)
    in RCTView (at View.js:32)
    in View (at EditProfileScreen.js:200)
    in RCTView (at View.js:32)
    in View (at MainLayout.js:51)
    in RCTScrollContentView (at ScrollView.js:1682)
    in RCTScrollView (at ScrollView.js:1800)
    in ScrollView (at ScrollView.js:1826)
    in ScrollView (at KeyboardAwareHOC.js:537)
    in KeyboardAwareScrollView (at MainLayout.js:45)
    in MainLayout (at EditProfileScreen.js:199)
    in EditProfileScreen (at SceneView.tsx:132)
    in StaticContainer
    in EnsureSingleNavigator (at SceneView.tsx:124)
    in SceneView (at useDescriptors.tsx:218)
    in RCTView (at View.js:32)
    in View (at DebugContainer.native.tsx:27)
    in DebugContainer (at NativeStackView.native.tsx:82)
    in MaybeNestedStack (at NativeStackView.native.tsx:326)
    in RCTView (at View.js:32)
    in View (at NativeStackView.native.tsx:319)
    in RNSScreen (at createAnimatedComponent.js:211)
    in AnimatedComponent (at createAnimatedComponent.js:264)
    in AnimatedComponentWrapper (at src/index.native.tsx:311)
    in Suspender (at src/index.tsx:40)
    in Suspense (at src/index.tsx:39)
    in Freeze (at src/index.native.tsx:203)
    in DelayedFreeze (at src/index.native.tsx:310)
    in InnerScreen (at src/index.native.tsx:567)
    in Screen (at NativeStackView.native.tsx:244)
    in SceneView (at NativeStackView.native.tsx:385)
    in Suspender (at src/index.tsx:40)
    in Suspense (at src/index.tsx:39)
    in Freeze (at src/index.native.tsx:203)
    in DelayedFreeze (at src/index.native.tsx:217)
    in RNSScreenStack (at src/index.native.tsx:224)
    in ScreenStack (at NativeStackView.native.tsx:373)
    in NativeStackViewInner (at NativeStackView.native.tsx:446)
    in RCTView (at View.js:32)
    in View (at SafeAreaProviderCompat.tsx:42)
    in SafeAreaProviderCompat (at NativeStackView.native.tsx:445)
    in NativeStackView (at createNativeStackNavigator.tsx:72)
    in PreventRemoveProvider (at useNavigationBuilder.tsx:718)
    in NavigationContent (at useComponent.tsx:35)
    in Unknown (at createNativeStackNavigator.tsx:71)
    in NativeStackNavigator (at mainRouter.js:46)
    in RNCSafeAreaView (at SafeAreaView.tsx:49)
    in RNCSafeAreaProvider (at SafeAreaContext.tsx:92)
    in EnsureSingleNavigator (at BaseNavigationContainer.tsx:430)
    in BaseNavigationContainer (at NavigationContainer.tsx:132)
    in ThemeProvider (at NavigationContainer.tsx:131)
    in NavigationContainerInner (at App.js:145)
    in RCTView (at View.js:32)
    in View (at App.js:144)
    in RCTView (at View.js:32)
    in View (at GestureHandlerRootView.tsx:20)
    in GestureHandlerRootView (at App.js:143)
    in App (at renderApplication.js:50)
    in RCTView (at View.js:32)
    in View (at AppContainer.js:92)
    in RCTView (at View.js:32)
    in View (at AppContainer.js:119)
    in AppContainer (at renderApplication.js:43)

**Smartphone (please complete the following information):**
 - OS: [iOS]
 - React Native version [e.g. 0.68.0]
 - react-native-date-picker version 4.1.2<=
 
 Please anyone help?

**Comment by henninghall** [comment] 2023-09-18 06:14
Duplicate of #404

**Closed by henninghall** 2023-09-18 06:14 UTC

**Comment by thachnqc2c** [comment] 2023-09-18 07:14
Hello henninghall. I'm facing this issue too, and I'm pretty sure none of solutions mentioned in https://github.com/henninghall/react-native-date-picker/issues/404 works. I see many issues have been created but nothing changed 🥲

**Comment by chetan-sevaro** [comment] 2023-11-20 06:59
@thachnqc2c You can try to manually add react-native-date-picker pod in your Podfile like below and then run pod install.

`pod 'react-native-date-picker', :path => '../node_modules/react-native-date-picker'`
