### ISSUE TITLE
android : View cannot be converted to NumberPickerView

### ISSUE THREAD

**Issue by khunghang16** [henninghall/react-native-date-picker#21] opened 2018-10-09 09:09 UTC
![screen shot 2018-10-09 at 4 09 01 pm](https://user-images.githubusercontent.com/27754944/46658784-b46c2f80-cbdd-11e8-8117-86f92767e296.png)

**Comment by Alex-DG** [comment] 2018-10-09 16:10
Hi @khunghang16 ,

If you go to `com.henninghall.date_picker/wheels/Wheel.java`

Go to line 35 and cast your view to NumberPickerView:
`this.picker = (NumberPickerView) pickerView.findViewById(id);`

It should fix your issue.

**Comment by khunghang16** [comment] 2018-10-10 08:30
install version 2.0.0 and fix it .

**Comment by khunghang16** [comment] 2018-10-12 16:44
> Hi @khunghang16 ,
> 
> If you go to `com.henninghall.date_picker/wheels/Wheel.java`
> 
> Go to line 35 and cast your view to NumberPickerView:
> `this.picker = (NumberPickerView) pickerView.findViewById(id);`
> 
> It should fix your issue.

You can show me example 'cast your view to NumberPickerView'.tks

**Comment by henninghall** [comment] 2018-10-14 18:33
Thanks for reporting this. It is fixed in v2.1.1

**Closed by henninghall** 2018-10-14 18:33 UTC

**Comment by mxia** [comment] 2020-10-14 00:07
I'm seeing this issue on v3.2.4. It looks to be caused by commit https://github.com/henninghall/react-native-date-picker/commit/69ca7de49b12926f027bfb2a722ef5c09757ecb9. Reverting back to v3.2.0 works.

**Comment by henninghall** [comment] 2020-10-18 18:21
@mxia Please try the new v3.2.5, it's most likely fixed there

**Comment by mxia** [comment] 2020-10-19 05:36
@henninghall Thanks so much! It works.
