### ISSUE TITLE
Keyboard opens on focus for time picker. Does not Respond to Keyboard Aware View

### ISSUE THREAD

**Issue by ramsers** [henninghall/react-native-date-picker#573] opened 2022-10-12 20:01 UTC
**Describe the bug**
On Iphone 12 ios 16, when using mode="time" the keyboard appears when the timepicker is touched. Covering the timepicker and not responding to the keyboard aware view

**Expected behavior**
Ideally the keyboard should not appear at all and only allow the user to scroll through times.

**Smartphone (please complete the following information):**
 - OS: [iOS]
 - React Native version [e.g. 0.66.4]
 - react-native-date-picker version [e.g. 4.2.5]

**Comment by anieshka** [comment] 2023-03-29 06:44
> **Describe the bug** On Iphone 12 ios 16, when using mode="time" the keyboard appears when the timepicker is touched. Covering the timepicker and not responding to the keyboard aware view
> 
> **Expected behavior** Ideally the keyboard should not appear at all and only allow the user to scroll through times.
> 
> **Smartphone (please complete the following information):**
> 
> * OS: [iOS]
> * React Native version [e.g. 0.66.4]
> * react-native-date-picker version [e.g. 4.2.5]

I'm having the same issue as well, is there a solution to this?

**Comment by randhi-w** [comment] 2023-06-08 06:47
Having the same issue.

**Comment by saurabhg138** [comment] 2023-08-10 09:51
Any workaround?
or may be alternate library?

**Comment by henninghall** [comment] 2023-08-10 11:35
I saw this workaround, haven't tested it out, but might be worth doing if you're having issues with this
https://github.com/Alghurairinvestment/react-native-date-picker-zed/commit/de2e5e24eece5fe0c65f9e2d9273e089aab8cdd4

**Comment by saurabhg138** [comment] 2023-08-10 11:46
@henninghall I will require code change in library itself right? We are trying to avoid this.

**Comment by saurabhg138** [comment] 2023-09-14 08:19
@henninghall Any timeline for this issue fix?

**Comment by henninghall** [comment] 2023-09-14 08:56
@saurabhg138 there is no timeline, PRs are welcome!

**Comment by jagdeepChicmic** [comment] 2023-12-19 06:19
any solution for this? @henninghall

**Comment by huydosgtech** [comment] 2023-12-19 09:42
Please review my PR @henninghall : https://github.com/henninghall/react-native-date-picker/pull/743

**Comment by henninghall** [comment] 2023-12-19 09:49
I don't think I understand this issue. To me it makes perfect sense to be able to both input time by scrolling and using the keyboard. This seems to be the intended behaviour by apple's design. 

https://github.com/henninghall/react-native-date-picker/assets/1652607/97a7b2aa-e45a-4691-b73c-df4e1490e9be

Am I missing something?

**Comment by henninghall** [comment] 2023-12-22 13:55
Works fine with modals too where the keyboard pushes the modal up when appearing:

https://github.com/henninghall/react-native-date-picker/assets/1652607/c8436d38-5b69-402d-a5be-b894e50a405a

I will close this issue until someone can show an example of where this is an actual problem.

**Closed by henninghall** 2023-12-22 13:55 UTC

**Comment by mohamedmagdy7** [comment] 2024-06-10 20:51
having same issue, have anyone managed to solve it?

**Comment by fcformal42** [comment] 2025-11-19 11:07
<img width="423" height="383" alt="Image" src="https://github.com/user-attachments/assets/c7d7f666-4fd8-4bd4-8b64-a1a3b757bd0e" />

<img width="414" height="364" alt="Image" src="https://github.com/user-attachments/assets/ff40120e-60dc-4e49-8721-15f68397b5a5" />
i am getting this the keybaord hiding the time

**Comment by iformal42** [comment] 2025-11-19 11:37
> Works fine with modals too where the keyboard pushes the modal up when appearing:
> 
>  291554239-3c231c1b-fece-4057-91d6-84cfb31d9f63.mov 
> I will close this issue until someone can show an example of where this is an actual problem.
how does yours keypad pushes the time spinner above
