### ISSUE TITLE
Cancel (onCancel func) button is not visible in Ipad 

### ISSUE THREAD

**Issue by selfishprogrammer** [henninghall/react-native-date-picker#511] opened 2022-05-02 10:45 UTC
**Describe the bug**
When i am running Application on Ipad pro Cancel button is not showing.

**Expected behavior**
Cancel Button Should be visible in IPAD

**Smartphone (please complete the following information):**
 - OS: [Android or iOS]
 - React Native version [e.g. 0.59.4]
 - react-native-date-picker version [e.g. 2.5.1]
<img width="369" alt="Screenshot 2022-05-02 at 4 14 42 PM" src="https://user-images.githubusercontent.com/58311914/166222340-1551fe58-4c22-4486-9d12-2055d20ef8d6.png">

**Comment by tancred27** [comment] 2022-06-20 09:00
I am facing the same issue. Have you found a fix for it ? @selfishprogrammer

**Comment by selfishprogrammer** [comment] 2022-06-21 21:44
> I am facing the same issue. Have you found a fix for it ? @selfishprogrammer

No didn’t found any solution , using other datepicker

**Comment by tancred27** [comment] 2022-06-23 05:38
Could you tell me which one you're using ? 
Also, does the picker appear at the bottom of the screen for you like in iphones ? It does not appear at the bottom on an ipad for me. @selfishprogrammer

**Comment by tancred27** [comment] 2022-06-23 05:38
> > I am facing the same issue. Have you found a fix for it ? @selfishprogrammer
> 
> No didn’t found any solution , using other datepicker

Could you tell me which one you're using ? 
Also, does the picker appear at the bottom of the screen for you like in iphones ? It does not appear at the bottom on an ipad for me. @selfishprogrammer

**Comment by henninghall** [comment] 2022-06-23 06:46
I am not sure, but I believe this is the desired look on iPads. Nothing in the code tells iPads to remove the cancel button, the native iOS components are used directly and removing this by themselves. To cancel on iPads I think you are expected to tap outside of an alert.

Would be great if someone with knowledge about iPad design guidelines can confirm this 🙂

**Comment by tancred27** [comment] 2022-06-23 07:06
> I am not sure, but I believe this is the desired look on iPads. Nothing in the code tells iPads to remove the cancel button, the native iOS components are used directly and removing this by themselves. To cancel on iPads I think you are expected to tap outside of an alert.
> 
> Would be great if someone with knowledge about iPad design guidelines can confirm this 🙂

What about the position of the picker ?
![MicrosoftTeams-image](https://user-images.githubusercontent.com/55374925/175236549-a18993d9-9383-45b1-bee8-6eda0a02ea69.png)

This is how it is appearing which I am pressing on the time button.
Is there a way to make it appear at the bottom of the screen like it does on other ios devices ?

**Comment by selfishprogrammer** [comment] 2022-06-24 12:30
> > > I am facing the same issue. Have you found a fix for it ? @selfishprogrammer
> > 
> > 
> > No didn’t found any solution , using other datepicker
> 
> Could you tell me which one you're using ? Also, does the picker appear at the bottom of the screen for you like in iphones ? It does not appear at the bottom on an ipad for me.

i am using **react-native-modal-datetime-picker** for now .
and it appears  on bottom of the Screen IOS.

**Comment by tancred27** [comment] 2022-07-07 03:57
> > > > I am facing the same issue. Have you found a fix for it ? @selfishprogrammer
> > > 
> > > 
> > > No didn’t found any solution , using other datepicker
> > 
> > 
> > Could you tell me which one you're using ? Also, does the picker appear at the bottom of the screen for you like in iphones ? It does not appear at the bottom on an ipad for me.
> 
> i am using **react-native-modal-datetime-picker** for now . and it appears on bottom of the Screen IOS. @tancred27

Alright, thank you @selfishprogrammer

**Comment by henninghall** [comment] 2022-07-15 21:25
@tancred27 That position looks weird, it is supposed to be in the middle like this: https://user-images.githubusercontent.com/1652607/179312078-4ef1c669-49aa-4411-aefd-c8762bd6ca3d.png

Since that is another problem could you please create another issue and explain how to reproduce that? 
I am closing this one since cancel button seems to be intentionally removed on iPads.

**Closed by henninghall** 2022-07-15 21:25 UTC
