### ISSUE TITLE
 Could not find com.github.henninghall:numberpickerview:v1.1.5.

### ISSUE THREAD

**Issue by Kartik18g** [henninghall/react-native-date-picker#640] opened 2023-04-12 19:04 UTC
**Describe the bug**
Build fails with ` Could not find com.github.henninghall:numberpickerview:v1.1.5.` 

 - OS: MacOS Android build
 - React Native version 0.67.2
 - react-native-date-picker version [e.g. 4.2.10]

**Comment by henninghall** [comment] 2023-04-12 19:18
Jitpack is down at the moment https://www.saashub.com/jitpack-status

**Comment by henninghall** [comment] 2023-04-12 19:23
Duplicate of https://github.com/henninghall/react-native-date-picker/issues/396

**Closed by henninghall** 2023-04-12 19:23 UTC

**Comment by Kartik18g** [comment] 2023-04-12 19:34
@henninghall 
Adding this to build.gradle is necessary for android builds to succeed. Can't we add this into the setup guide ?
```maven { url 'https://www.jitpack.io' }```

**Comment by lucaszdev** [comment] 2023-05-03 20:48
@Kartik18g  Still with problem
