### ISSUE TITLE
Cannot run on ios with react native 0.63.2

### ISSUE THREAD

**Issue by manastasiou** [henninghall/react-native-date-picker#246] opened 2020-09-24 21:12 UTC
I am getting the following error while trying to run the ios

```
node_modules/react-native-date-picker/ios/RNDatePicker/DatePicker.m:58:18: error: property 'preferredDatePickerStyle' not found on object of type 'DatePicker *'
            self.preferredDatePickerStyle = UIDatePickerStyleWheels;
```

i have the latest version of react native
    "react-native": "^0.63.2"

And i also get this
```
react-native-date-picker/ios/RNDatePicker/DatePicker.m:58:45: error: use of undeclared identifier 'UIDatePickerStyleWheels'
            self.preferredDatePickerStyle = UIDatePickerStyleWheels;
```

**Comment by henninghall** [comment] 2020-09-26 07:58
Duplicate of https://github.com/henninghall/react-native-date-picker/issues/224

**Closed by henninghall** 2020-09-26 07:58 UTC
