### ISSUE TITLE
AndroidVariant Props to support like 'iosClone' behaviour is missing from Library 5.0.0 and above

### ISSUE THREAD

**Issue by faizankh4** [henninghall/react-native-date-picker#869] opened 2024-11-25 06:37 UTC
**Describe the bug**
Through our app disable people can book assistance for their self. But to Provide Support for android 14 we have to increase our library from 4.0.0 to 5.0.0 and above. In newer Library we don't have support like 'iosClone' behaviour. so It is very hard for blind people to set Time with android native behaviour when Talk back on.

**Expected behavior**
How can we achieve better accessibility in new Library when Talkback is on .Like 'iosClone' 

**Smartphone (please complete the following information):**
 - OS: [Android ]
 - React Native version [0.64.2]
 - react-native-date-picker version [5.0.7]

**Comment by henninghall** [comment] 2024-12-07 10:29
Duplicate of https://github.com/henninghall/react-native-date-picker/issues/792

**Closed by henninghall** 2024-12-07 10:29 UTC
