### ISSUE TITLE
View config not found for name RNDatePicker

### ISSUE THREAD

**Issue by approached** [henninghall/react-native-date-picker#182] opened 2020-04-15 09:45 UTC
Package has no dependencies in package.json.

**Describe the bug**
I become a error:
```
View config not found for name RNDatePicker

This error is located at:
    in RNDatePicker (at DatePickerIOS.js:31)
```

**Solution**
```
yarn add @react-native-community/datetimepicker
```

**Smartphone (please complete the following information):**
 - OS: IOS
 - React Native version 60.1
 - react-native-date-picker version 2.7.9

**Comment by henninghall** [comment] 2020-04-16 05:32
Duplicate of https://github.com/henninghall/react-native-date-picker/issues/107

**Closed by henninghall** 2020-04-16 05:32 UTC
