### ISSUE TITLE
TypeError: null is not an object (evaluating '_reactNative.NativeModules.RNDatePicker.openPicker')

### ISSUE THREAD

**Issue by hpardess** [henninghall/react-native-date-picker#445] opened 2021-12-30 20:14 UTC
**Describe the bug**
```
TypeError: null is not an object (evaluating '_reactNative.NativeModules.RNDatePicker.openPicker')

This error is located at:
    in DatePickerAndroid (at src/index.js:19)
    in DatePickerWrapper (at App.js:224)
    in RCTView (at View.js:32)
```

**To Reproduce**
Add example code that reproduces the behavior. 
```javascript
const App = ({ route, navigation }) => {

  const [currentDate, setCurrentDate] = React.useState(new Date());
  const [showDatePicker, setShowDatePicker] = React.useState(false);

  return (
                <TouchableOpacity
                    activeOpacity={0.9}
                    onPress={() => {setShowDatePicker(true)}}>
                    <MaterialIcons name="add" size={24} color={Colors.primaryColor} />
                </TouchableOpacity>
                <DatePicker modal open={showDatePicker} date={currentDate}
                    onConfirm={(date) => {
                        setShowDatePicker(false)
                        console.log("add date to holidays array", date)
                    }}
                    onCancel={() => {
                        setShowDatePicker(false)
                    }}/>
)

}
export default App;
```

**Smartphone (please complete the following information):**
 - OS: Android
 - React Native version 0.66.4
 - react-native-date-picker version ^4.1.3

**Comment by henninghall** [comment] 2021-12-30 20:20
duplicate of https://github.com/henninghall/react-native-date-picker/issues/404

**Closed by henninghall** 2021-12-30 20:20 UTC

**Comment by Goowwy** [comment] 2022-05-21 03:15
where is completed? i didnt find solution
