### ISSUE TITLE
TypeError: null is not an object (evaluating '_reactNative.NativeModules.RNDatePickerManager.openPicker')

### ISSUE THREAD

**Issue by Elunir** [henninghall/react-native-date-picker#487] opened 2022-04-02 22:13 UTC
This error is located at:
    in DatePickerIOS (created by DatePickerWrapper)
    in DatePickerWrapper (created by AlarmScreen)
    in RCTScrollContentView (created by ScrollView)
    in RCTScrollView (created by ScrollView)
    in ScrollView (created by ScrollView)
    in ScrollView (created by ScreenWithScrolling)
    in RCTView (created by View)
    in View (created by ScreenWithScrolling)
    in RCTView (created by View)
    in View (created by KeyboardAvoidingView)
    in KeyboardAvoidingView (created by ScreenWithScrolling)
    in ScreenWithScrolling (created by Screen)
    in Screen (created by AlarmScreen)
    in AlarmScreen (created by SceneView)
    in StaticContainer
    in EnsureSingleNavigator (created by SceneView)
    in SceneView (created by SceneView)
    in RCTView (created by View)
    in View (created by DebugContainer)
    in DebugContainer (created by MaybeNestedStack)
    in MaybeNestedStack (created by SceneView)
    in RNSScreen (created by AnimatedComponent)
    in AnimatedComponent
    in AnimatedComponentWrapper (created by Screen)
    in Screen (created by SceneView)
    in SceneView (created by NativeStackViewInner)
    in RNSScreenStack (created by NativeStackViewInner)
    in NativeStackViewInner (created by NativeStackView)
    in RCTView (created by View)
    in View (created by SafeAreaInsetsContext)
    in SafeAreaProviderCompat (created by NativeStackView)
    in NativeStackView (created by NativeStackNavigator)
    in Unknown (created by NativeStackNavigator)
    in NativeStackNavigator (created by AppStack)
    in AppStack (created by AppNavigator)
    in EnsureSingleNavigator
    in BaseNavigationContainer
    in ThemeProvider
    in NavigationContainerInner (created by AppNavigator)
    in AppNavigator (created by App)
    in ErrorBoundary (created by App)
    in RNCSafeAreaProvider (created by SafeAreaProvider)
    in SafeAreaProvider (created by App)
    in ToggleStorybook (created by App)
    in App (created by ExpoRoot)
    in ExpoRoot
    in RCTView (created by View)
    in View (created by AppContainer)
    in DevAppContainer (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:104:6 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:172:19 in handleException
at node_modules/react-native/Libraries/Core/ReactFiberErrorDialog.js:43:2 in showErrorDialog

**Comment by christian-hess-94** [comment] 2022-04-08 20:40
I'm also having this error when running in simulators in macbook pros that have the M1 chip.

This also crashes the app when running it through an expo development build

**Comment by henninghall** [comment] 2022-04-15 14:25
Duplicate of https://github.com/henninghall/react-native-date-picker/issues/404

**Closed by henninghall** 2022-04-15 14:25 UTC
