### ISSUE TITLE
can not found RNDatePicker

### ISSUE THREAD

**Issue by zhichao-github** [henninghall/react-native-date-picker#386] opened 2021-09-09 02:14 UTC
**Describe the bug**
Invariant Violation: requireNativeComponent: "RNDatePicker" was not found in the UIManager.

**Expected behavior**
fix it

**To Reproduce**
Add example code that reproduces the behavior. 
```javascript
export default class App extends Component {

  state = { date: new Date() }

  render = () =>
    <DatePicker
      date={this.state.date}
      onDateChange={date => this.setState({ date })}
    />

}
```

**Smartphone (please complete the following information):**
 - OS: [iOS]
 - React Native version [e.g. 0.59.4]
 - react-native-date-picker version [e.g. 2.5.1]

**Comment by henninghall** [comment] 2021-10-02 09:45
Duplicate of https://github.com/henninghall/react-native-date-picker/issues/107

**Closed by henninghall** 2021-10-02 09:45 UTC
