### ISSUE TITLE
TextColor property not changing "Today" in iOS

### ISSUE THREAD

**Issue by LaraMateo** [henninghall/react-native-date-picker#619] opened 2023-02-28 23:00 UTC
**Describe the bug**
When setting textColor property to green in iOS, all the text change except the "Today" text in the calendar.  

![image](https://user-images.githubusercontent.com/73840306/222001552-30c5bd18-72a6-4e0b-b0bc-c16e9f0a6e9e.png)

**Expected behavior**
"Today" is changed by its corresponding date 

![image](https://user-images.githubusercontent.com/73840306/222002447-9d5c7fae-f162-4b56-b120-e1f0d2f1be1d.png)

**To Reproduce**
```javascript
<DatePicker
date={value}
mode="datetime"
fadeToColor="none"
is24hourSource="locale"
onDateChange={onChange}
textColor={colors.primary}
locale={configContext?.language}
 />
```

**Smartphone:**
 - OS: iOS 16.1
 - React Native version 0.70.6
 - react-native-date-picker version ^4.2.9

**Comment by henninghall** [comment] 2023-03-01 07:02
Which iOS version are you on?

**Comment by LaraMateo** [comment] 2023-03-02 15:30
> Which iOS version are you on?

16.1

**Comment by henninghall** [comment] 2023-09-10 12:54
This seem to have been fixed in a later version of iOS. I cannot reproduce it in 16.4 at least. Let me know if it is still an issue and we can reopen this.

**Closed by henninghall** 2023-09-10 12:54 UTC

**Comment by NikolakoG** [comment] 2023-09-29 12:04
If you add {color: textColor} in line 24 of DatePickerIOS.js file, the problem seems to be resolved even in lower versions of iOS. (My solution works in 16.0 version of ios)
![Screenshot 2023-09-29 at 3 02 48 PM](https://github.com/henninghall/react-native-date-picker/assets/82265756/ae86a12c-00f5-432e-bf2c-38a4f2b8d7f6)
