### ISSUE TITLE
Have  a error

### ISSUE THREAD

**Issue by xq25257** [henninghall/react-native-date-picker#649] opened 2023-04-24 10:03 UTC
**Describe the bug**
Invariant Violation: requireNativeComponent: "RNDatePicker" was not found in the UIManager.

**Expected behavior**

**To Reproduce**
import DatePicker from "react-native-date-picker";
```javascript
class DatePickerView extends Component {
  render = () =>
    <DatePicker mode={'datetime'} date={new Date()} onDateChange={()=>{}} />
}
```

**Smartphone (please complete the following information):**
 - OS:  iOS
 - React Native version [e.g. 0.70.0]
 - react-native-date-picker version [e.g. 4.2.12]

**Comment by henninghall** [comment] 2023-04-24 10:15
Duplicate of https://github.com/henninghall/react-native-date-picker/issues/44

**Closed by henninghall** 2023-04-24 10:15 UTC
